spring:
  cloud:
    stream:
      function:
        definition: developerCountryToDeveloperJoin;developerCountryDeveloperToCountryJoin;consumeFinalMessage
      bindings:
        developerCountryToDeveloperJoin-in-0:
          destination: developer-country
          group: testJoinGrp
        developerCountryToDeveloperJoin-in-1:
          destination: developer
          group: testJoinGrp
        developerCountryToDeveloperJoin-out-0:
          destination: developercountry-to-developer
        developerCountryDeveloperToCountryJoin-in-0:
          destination: developercountry-to-developer
          group: testJoinGrp
        developerCountryDeveloperToCountryJoin-in-1:
          destination: country
          group: testJoinGrp
        developerCountryDeveloperToCountryJoin-out-0:
          destination: developercountrydeveloper-to-country
        consumeFinalMessage-in-0:
          destination: developercountrydeveloper-to-country
          group: testJoinGrp



      kafka:
        bindings:
        streams:
          binder:
            configuration:
              schema.registry.url: http://localhost:8081
              specific.avro.reader: true
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde



