/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zabeer.joins.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Developer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1171279399140511166L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Developer\",\"namespace\":\"com.zabeer.joins.model\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"experienceLevel\",\"type\":\"string\"},{\"name\":\"skill\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Developer> ENCODER =
      new BinaryMessageEncoder<Developer>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Developer> DECODER =
      new BinaryMessageDecoder<Developer>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Developer> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Developer> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Developer> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Developer>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Developer to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Developer from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Developer instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Developer fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence id;
   private java.lang.CharSequence name;
   private java.lang.CharSequence experienceLevel;
   private java.lang.CharSequence skill;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Developer() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param experienceLevel The new value for experienceLevel
   * @param skill The new value for skill
   */
  public Developer(java.lang.CharSequence id, java.lang.CharSequence name, java.lang.CharSequence experienceLevel, java.lang.CharSequence skill) {
    this.id = id;
    this.name = name;
    this.experienceLevel = experienceLevel;
    this.skill = skill;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return experienceLevel;
    case 3: return skill;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: experienceLevel = (java.lang.CharSequence)value$; break;
    case 3: skill = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'experienceLevel' field.
   * @return The value of the 'experienceLevel' field.
   */
  public java.lang.CharSequence getExperienceLevel() {
    return experienceLevel;
  }


  /**
   * Sets the value of the 'experienceLevel' field.
   * @param value the value to set.
   */
  public void setExperienceLevel(java.lang.CharSequence value) {
    this.experienceLevel = value;
  }

  /**
   * Gets the value of the 'skill' field.
   * @return The value of the 'skill' field.
   */
  public java.lang.CharSequence getSkill() {
    return skill;
  }


  /**
   * Sets the value of the 'skill' field.
   * @param value the value to set.
   */
  public void setSkill(java.lang.CharSequence value) {
    this.skill = value;
  }

  /**
   * Creates a new Developer RecordBuilder.
   * @return A new Developer RecordBuilder
   */
  public static com.zabeer.joins.model.Developer.Builder newBuilder() {
    return new com.zabeer.joins.model.Developer.Builder();
  }

  /**
   * Creates a new Developer RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Developer RecordBuilder
   */
  public static com.zabeer.joins.model.Developer.Builder newBuilder(com.zabeer.joins.model.Developer.Builder other) {
    if (other == null) {
      return new com.zabeer.joins.model.Developer.Builder();
    } else {
      return new com.zabeer.joins.model.Developer.Builder(other);
    }
  }

  /**
   * Creates a new Developer RecordBuilder by copying an existing Developer instance.
   * @param other The existing instance to copy.
   * @return A new Developer RecordBuilder
   */
  public static com.zabeer.joins.model.Developer.Builder newBuilder(com.zabeer.joins.model.Developer other) {
    if (other == null) {
      return new com.zabeer.joins.model.Developer.Builder();
    } else {
      return new com.zabeer.joins.model.Developer.Builder(other);
    }
  }

  /**
   * RecordBuilder for Developer instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Developer>
    implements org.apache.avro.data.RecordBuilder<Developer> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence name;
    private java.lang.CharSequence experienceLevel;
    private java.lang.CharSequence skill;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zabeer.joins.model.Developer.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.experienceLevel)) {
        this.experienceLevel = data().deepCopy(fields()[2].schema(), other.experienceLevel);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.skill)) {
        this.skill = data().deepCopy(fields()[3].schema(), other.skill);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Developer instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zabeer.joins.model.Developer other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.experienceLevel)) {
        this.experienceLevel = data().deepCopy(fields()[2].schema(), other.experienceLevel);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.skill)) {
        this.skill = data().deepCopy(fields()[3].schema(), other.skill);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.zabeer.joins.model.Developer.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.zabeer.joins.model.Developer.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.zabeer.joins.model.Developer.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.zabeer.joins.model.Developer.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'experienceLevel' field.
      * @return The value.
      */
    public java.lang.CharSequence getExperienceLevel() {
      return experienceLevel;
    }


    /**
      * Sets the value of the 'experienceLevel' field.
      * @param value The value of 'experienceLevel'.
      * @return This builder.
      */
    public com.zabeer.joins.model.Developer.Builder setExperienceLevel(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.experienceLevel = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'experienceLevel' field has been set.
      * @return True if the 'experienceLevel' field has been set, false otherwise.
      */
    public boolean hasExperienceLevel() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'experienceLevel' field.
      * @return This builder.
      */
    public com.zabeer.joins.model.Developer.Builder clearExperienceLevel() {
      experienceLevel = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'skill' field.
      * @return The value.
      */
    public java.lang.CharSequence getSkill() {
      return skill;
    }


    /**
      * Sets the value of the 'skill' field.
      * @param value The value of 'skill'.
      * @return This builder.
      */
    public com.zabeer.joins.model.Developer.Builder setSkill(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.skill = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'skill' field has been set.
      * @return True if the 'skill' field has been set, false otherwise.
      */
    public boolean hasSkill() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'skill' field.
      * @return This builder.
      */
    public com.zabeer.joins.model.Developer.Builder clearSkill() {
      skill = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Developer build() {
      try {
        Developer record = new Developer();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.experienceLevel = fieldSetFlags()[2] ? this.experienceLevel : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.skill = fieldSetFlags()[3] ? this.skill : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Developer>
    WRITER$ = (org.apache.avro.io.DatumWriter<Developer>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Developer>
    READER$ = (org.apache.avro.io.DatumReader<Developer>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.name);

    out.writeString(this.experienceLevel);

    out.writeString(this.skill);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.experienceLevel = in.readString(this.experienceLevel instanceof Utf8 ? (Utf8)this.experienceLevel : null);

      this.skill = in.readString(this.skill instanceof Utf8 ? (Utf8)this.skill : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 2:
          this.experienceLevel = in.readString(this.experienceLevel instanceof Utf8 ? (Utf8)this.experienceLevel : null);
          break;

        case 3:
          this.skill = in.readString(this.skill instanceof Utf8 ? (Utf8)this.skill : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










