/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zabeer.joins.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DeveloperCountry extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2566798454942519262L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeveloperCountry\",\"namespace\":\"com.zabeer.joins.model\",\"fields\":[{\"name\":\"developerId\",\"type\":\"string\"},{\"name\":\"countryId\",\"type\":\"string\"},{\"name\":\"relation\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DeveloperCountry> ENCODER =
      new BinaryMessageEncoder<DeveloperCountry>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DeveloperCountry> DECODER =
      new BinaryMessageDecoder<DeveloperCountry>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DeveloperCountry> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DeveloperCountry> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DeveloperCountry> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DeveloperCountry>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DeveloperCountry to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DeveloperCountry from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DeveloperCountry instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DeveloperCountry fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence developerId;
   private java.lang.CharSequence countryId;
   private java.lang.CharSequence relation;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeveloperCountry() {}

  /**
   * All-args constructor.
   * @param developerId The new value for developerId
   * @param countryId The new value for countryId
   * @param relation The new value for relation
   */
  public DeveloperCountry(java.lang.CharSequence developerId, java.lang.CharSequence countryId, java.lang.CharSequence relation) {
    this.developerId = developerId;
    this.countryId = countryId;
    this.relation = relation;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return developerId;
    case 1: return countryId;
    case 2: return relation;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: developerId = (java.lang.CharSequence)value$; break;
    case 1: countryId = (java.lang.CharSequence)value$; break;
    case 2: relation = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'developerId' field.
   * @return The value of the 'developerId' field.
   */
  public java.lang.CharSequence getDeveloperId() {
    return developerId;
  }


  /**
   * Sets the value of the 'developerId' field.
   * @param value the value to set.
   */
  public void setDeveloperId(java.lang.CharSequence value) {
    this.developerId = value;
  }

  /**
   * Gets the value of the 'countryId' field.
   * @return The value of the 'countryId' field.
   */
  public java.lang.CharSequence getCountryId() {
    return countryId;
  }


  /**
   * Sets the value of the 'countryId' field.
   * @param value the value to set.
   */
  public void setCountryId(java.lang.CharSequence value) {
    this.countryId = value;
  }

  /**
   * Gets the value of the 'relation' field.
   * @return The value of the 'relation' field.
   */
  public java.lang.CharSequence getRelation() {
    return relation;
  }


  /**
   * Sets the value of the 'relation' field.
   * @param value the value to set.
   */
  public void setRelation(java.lang.CharSequence value) {
    this.relation = value;
  }

  /**
   * Creates a new DeveloperCountry RecordBuilder.
   * @return A new DeveloperCountry RecordBuilder
   */
  public static com.zabeer.joins.model.DeveloperCountry.Builder newBuilder() {
    return new com.zabeer.joins.model.DeveloperCountry.Builder();
  }

  /**
   * Creates a new DeveloperCountry RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeveloperCountry RecordBuilder
   */
  public static com.zabeer.joins.model.DeveloperCountry.Builder newBuilder(com.zabeer.joins.model.DeveloperCountry.Builder other) {
    if (other == null) {
      return new com.zabeer.joins.model.DeveloperCountry.Builder();
    } else {
      return new com.zabeer.joins.model.DeveloperCountry.Builder(other);
    }
  }

  /**
   * Creates a new DeveloperCountry RecordBuilder by copying an existing DeveloperCountry instance.
   * @param other The existing instance to copy.
   * @return A new DeveloperCountry RecordBuilder
   */
  public static com.zabeer.joins.model.DeveloperCountry.Builder newBuilder(com.zabeer.joins.model.DeveloperCountry other) {
    if (other == null) {
      return new com.zabeer.joins.model.DeveloperCountry.Builder();
    } else {
      return new com.zabeer.joins.model.DeveloperCountry.Builder(other);
    }
  }

  /**
   * RecordBuilder for DeveloperCountry instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeveloperCountry>
    implements org.apache.avro.data.RecordBuilder<DeveloperCountry> {

    private java.lang.CharSequence developerId;
    private java.lang.CharSequence countryId;
    private java.lang.CharSequence relation;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.zabeer.joins.model.DeveloperCountry.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.developerId)) {
        this.developerId = data().deepCopy(fields()[0].schema(), other.developerId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.countryId)) {
        this.countryId = data().deepCopy(fields()[1].schema(), other.countryId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.relation)) {
        this.relation = data().deepCopy(fields()[2].schema(), other.relation);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing DeveloperCountry instance
     * @param other The existing instance to copy.
     */
    private Builder(com.zabeer.joins.model.DeveloperCountry other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.developerId)) {
        this.developerId = data().deepCopy(fields()[0].schema(), other.developerId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.countryId)) {
        this.countryId = data().deepCopy(fields()[1].schema(), other.countryId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.relation)) {
        this.relation = data().deepCopy(fields()[2].schema(), other.relation);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'developerId' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeveloperId() {
      return developerId;
    }


    /**
      * Sets the value of the 'developerId' field.
      * @param value The value of 'developerId'.
      * @return This builder.
      */
    public com.zabeer.joins.model.DeveloperCountry.Builder setDeveloperId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.developerId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'developerId' field has been set.
      * @return True if the 'developerId' field has been set, false otherwise.
      */
    public boolean hasDeveloperId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'developerId' field.
      * @return This builder.
      */
    public com.zabeer.joins.model.DeveloperCountry.Builder clearDeveloperId() {
      developerId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'countryId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCountryId() {
      return countryId;
    }


    /**
      * Sets the value of the 'countryId' field.
      * @param value The value of 'countryId'.
      * @return This builder.
      */
    public com.zabeer.joins.model.DeveloperCountry.Builder setCountryId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.countryId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'countryId' field has been set.
      * @return True if the 'countryId' field has been set, false otherwise.
      */
    public boolean hasCountryId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'countryId' field.
      * @return This builder.
      */
    public com.zabeer.joins.model.DeveloperCountry.Builder clearCountryId() {
      countryId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'relation' field.
      * @return The value.
      */
    public java.lang.CharSequence getRelation() {
      return relation;
    }


    /**
      * Sets the value of the 'relation' field.
      * @param value The value of 'relation'.
      * @return This builder.
      */
    public com.zabeer.joins.model.DeveloperCountry.Builder setRelation(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.relation = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'relation' field has been set.
      * @return True if the 'relation' field has been set, false otherwise.
      */
    public boolean hasRelation() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'relation' field.
      * @return This builder.
      */
    public com.zabeer.joins.model.DeveloperCountry.Builder clearRelation() {
      relation = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeveloperCountry build() {
      try {
        DeveloperCountry record = new DeveloperCountry();
        record.developerId = fieldSetFlags()[0] ? this.developerId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.countryId = fieldSetFlags()[1] ? this.countryId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.relation = fieldSetFlags()[2] ? this.relation : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DeveloperCountry>
    WRITER$ = (org.apache.avro.io.DatumWriter<DeveloperCountry>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DeveloperCountry>
    READER$ = (org.apache.avro.io.DatumReader<DeveloperCountry>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.developerId);

    out.writeString(this.countryId);

    out.writeString(this.relation);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.developerId = in.readString(this.developerId instanceof Utf8 ? (Utf8)this.developerId : null);

      this.countryId = in.readString(this.countryId instanceof Utf8 ? (Utf8)this.countryId : null);

      this.relation = in.readString(this.relation instanceof Utf8 ? (Utf8)this.relation : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.developerId = in.readString(this.developerId instanceof Utf8 ? (Utf8)this.developerId : null);
          break;

        case 1:
          this.countryId = in.readString(this.countryId instanceof Utf8 ? (Utf8)this.countryId : null);
          break;

        case 2:
          this.relation = in.readString(this.relation instanceof Utf8 ? (Utf8)this.relation : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










